# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

    # Set up deep sleep + hibernation
  # swapDevices = [
  #   { device = "/swapfile"; }
  # ];
  # # Partition swapfile is on (after LUKS decryption)
  # boot.resumeDevice = "/dev/disk/by-uuid/05032ea4-beb1-4237-ac66-ab0bf79f39a7";
  # # Resume Offset is offset of swapfile
  # # https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Hibernation_into_swap_file
  # boot.kernelParams = [ "mem_sleep_default=deep" "resume_offset=80424960" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e821bff2-5f50-4ddb-a9ed-fde547beb0cf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4fda9725-766b-4810-b854-ee9bd36b50e0".device = "/dev/disk/by-uuid/4fda9725-766b-4810-b854-ee9bd36b50e0";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/D3CC-FC12";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/78551d9a-5254-435e-957f-1d5db02025a4"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
