export XDG_CONFIG_HOME="$HOME/.config"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export EDITOR="nvim"
export VISUAL="nvim"

export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.































































# vim: fdm=marker:fdl=0 ai ts=2 sw=2 et sts=2 ft=sh
