#!/bin/bash

echo "bash_profile"

# When interactive, run bashrc {{{
[[ $- = *i* ]] && [[ -r $HOME/.bashrc ]] && . $HOME/.bashrc
# }}}
# X session {{{
[ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ] && exec startx
# }}}
# Java {{{
# export JAVA_HOME="$HOME/.jenv/versions/`jenv version-name`"
export "JAVA_HOME=\$(/usr/libexec/java_home -v1.8.0)"
# }}}



































































# vim: fdm=marker:fdl=0 ai ts=2 sw=2 et sts=2 ft=sh
